=== api-evangelist/oracle-goldengate/json-schema/oracle-goldengate-cloud-service-database-registration-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "DatabaseRegistration",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "displayName": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "compartmentId": {
      "type": "string"
    },
    "databaseId": {
      "type": "string"
    },
    "connectionString": {
      "type": "string"
    },
    "username": {
      "type": "string"
    },
    "fqdn": {
      "type": "string"
    },
    "lifecycleState": {
      "type": "string"
    },
    "timeCreated": {
      "type": "string"
    }
  }
}

=== api-evangelist/oracle-goldengate/examples/oracle-goldengate-cloud-service-database-registration-example.json
{
  "id": "abc123",
  "displayName": "example_value",
  "description": "A sample description.",
  "compartmentId": "500123",
  "databaseId": "500123",
  "connectionString": "example_value",
  "username": "example_value",
  "fqdn": "example_value",
  "lifecycleState": "example_value",
  "timeCreated": "example_value"
}
